name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run URDF extractor
      run: cargo run src/tests/data/fanuc/lrmate200ib_macro.xacro
    - name: Build without features
      run: cargo build --no-default-features --verbose
    - name: Run tests without features
      run: cargo test --no-default-features --verbose
    - name: Run URDF extractor once more
      run: cargo run




